FROM node:21-alpine
RUN npm install nbb -g
RUN mkdir -p /unminify
COPY . /unminify/
WORKDIR /unminify
RUN npm install
WORKDIR /unminify/workspaces/unminify-core
RUN npm install
WORKDIR /unminify/workspaces/unminify-gcp
RUN npm install
WORKDIR /unminify
EXPOSE 8080
ENTRYPOINT ["nbb", "--classpath", ".:./workspaces/core/src:./workspaces/gcp/src", "./workspaces/gcp/src/unminify/gcp.cljs"]